FROM alpine:3.8

RUN apk update && apk upgrade &&\
    apk add --no-cache maven

RUN apk add --no-cache terraform

RUN apk add --no-cache bash \
                       python2-dev \
                       py-pip && \
    apk add --no-cache --virtual=build gcc \
                                       libffi-dev \
                                       make \
                                       musl-dev \
                                       openssl-dev && \
    pip install --upgrade pip && \
    pip install --upgrade azure-cli && \
    pip install --upgrade databricks-cli && \
    apk del --purge build && \
    apk add --no-cache jq \
                       openssl

RUN apk add --no-cache nodejs \
                                nodejs-npm && \
    npm install -g @angular/cli && \
    apk del --purge nodejs-npm && \
    apk add --no-cache python3

